### ISSUE TITLE
doesnt work

### ISSUE THREAD

**Issue by deceased1** [Blank-c/Blankrypt#1]
it doesnt work

**Comment by Blank-c** [comment]
What doesn't work? Can you explain?

**Comment by Blank-c** [comment]
@deceased1

**Comment by Smug246** [comment]
mf didnt even try explaining

**Comment by Smug246** [comment]
@Blank-c  whats your discord

**Comment by Blank-c** [comment]
> @Blank-c whats your discord

Blank?#0886

**Comment by Smug246** [comment]
sent

**Comment by Blank-c** [comment]
Need more info
