### ISSUE TITLE
Adding an option to supress the logo

### ISSUE THREAD

**Issue by Smug246** [Blank-c/Blankrypt#2]
without it
![image](https://user-images.githubusercontent.com/99215486/198389328-c56888da-8363-4265-ac03-2d82929cd80b.png)

with it
![image](https://user-images.githubusercontent.com/99215486/198389410-c320fad7-d626-499f-a02d-ae209b41cb35.png)
microsoft doesnt detect it which is great.

Only thing i would say is to add another option eg. `-l remove` that removes the big logo and other info thats printed out in the cmd and make an option to name the output of the file. other than that. good job

**Comment by Smug246** [comment]
also mb i forgot to change the file names to start with a vt_

**Comment by addi00000** [comment]
Are you checking that Microsoft isn't timing out and adding the file to their database?

**Comment by Smug246** [comment]
> Are you checking that Microsoft isn't timing out and adding the file to their database?

how do i check. it says microsoft is undetected

**Comment by Blank-c** [comment]
> without it ![image](https://user-images.githubusercontent.com/99215486/198389328-c56888da-8363-4265-ac03-2d82929cd80b.png)
> 
> with it ![image](https://user-images.githubusercontent.com/99215486/198389410-c320fad7-d626-499f-a02d-ae209b41cb35.png) microsoft doesnt detect it which is great.
> 
> Only thing i would say is to add another option eg. `-l remove` that removes the big logo and other info thats printed out in the cmd and make an option to name the output of the file. other than that. good job

Hmmm...I'll think about it.

Also, for now, if you want to automate it with your script, you can make it run as another process, so everything will be printed on another window does not spoil the main console window

**Comment by Smug246** [comment]
okay. works well nicely otherwise
