### ISSUE TITLE
Virus Total

### ISSUE THREAD

**Issue by deceased1** [Blank-c/Blankrypt#4]
![image](https://user-images.githubusercontent.com/91875581/198858546-e98b8348-3f07-43b2-9ead-65e65e074912.png)
it says its a virus and I was wondering what is in the file that is couting it as a virus

**Comment by Blank-c** [comment]
The file is made up of two files. The builder and the stub (to which your files will be merged with). And that gives all those false positives.

**Comment by Blank-c** [comment]
You don't need to trust me if you don't want to (even tho its safe). You can always run suspicious files/programs on sandboxes too :)

**Comment by Blank-c** [comment]
Hybrid analysis results: https://www.hybrid-analysis.com/sample/314324ec98869cd02f856924ce7114cf00bf748a7ff1cf54657b0f749f468bc5/63580d3fbeb4503fed25691c
